@startuml

title __SECONDWORLDCHARACTER's Class Diagram__\n

  namespace gamesource {
    namespace State {
      namespace CharacterState {
        namespace secondWorldCharacter {
          class gamesource.State.CharacterState.secondWorldCharacter.goblinGirlState {
              - app : SimpleApplication
              - bip001 : Node
              - boy : Spatial
              - boyControl : CharacterControl
              - bullet : BulletAppState
              - capsuleShape : CapsuleCollisionShape
              - character : Node
              - height : float
              - lizard : BoundingVolume
              - modelY : float
              - physics : PhysicsSpace
              - place : Vector3f
              - radius : float
              - rootNode : Node
              - scene : Node
              - stepHeight : float
              + get()
              + goblinGirlState()
              + goblinGirlState()
              + goblinGirlState()
              + initModel()
              + initPhysics()
              # cleanup()
              # initialize()
              # onDisable()
              # onEnable()
          }
        }
      }
    }
  }
  

  namespace gamesource {
    namespace State {
      namespace CharacterState {
        namespace secondWorldCharacter {
          class gamesource.State.CharacterState.secondWorldCharacter.shanmanState {
              - app : SimpleApplication
              - bip001 : Node
              - boyControl : CharacterControl
              - bullet : BulletAppState
              - capsuleShape : CapsuleCollisionShape
              - character : Node
              - height : float
              - modelY : float
              - physics : PhysicsSpace
              - place : Vector3f
              - radius : float
              - rootNode : Node
              - scene : Node
              - shan : BoundingVolume
              - shanman : Spatial
              - stepHeight : float
              + get()
              + initModel()
              + initPhysics()
              + shanmanState()
              + shanmanState()
              + shanmanState()
              # cleanup()
              # initialize()
              # onDisable()
              # onEnable()
          }
        }
      }
    }
  }
  

  gamesource.State.CharacterState.secondWorldCharacter.goblinGirlState -up-|> com.jme3.app.state.BaseAppState
  gamesource.State.CharacterState.secondWorldCharacter.shanmanState -up-|> com.jme3.app.state.BaseAppState


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
