@startuml

title __PARTICLE's Class Diagram__\n

  namespace gamesource {
    namespace battleState.particle {
      class gamesource.battleState.particle.DamageParticle {
          {static} - blood : ParticleEmitter
          {static} + getParticle1()
          {static} + getParticle2()
          {static} + getParticle3()
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.particle {
      class gamesource.battleState.particle.KingSkeletonStateParticle {
          {static} - flash : ParticleEmitter
          {static} + getParticle1()
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.particle {
      class gamesource.battleState.particle.MPParticle {
          {static} - flame : ParticleEmitter
          {static} + getParticle1()
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.particle {
      class gamesource.battleState.particle.StuxnetStateParticle {
          {static} - flash : ParticleEmitter
          {static} + getParticle1()
      }
    }
  }
  





@enduml
