@startuml

title __CONTROL's Class Diagram__\n

  namespace gamesource {
    namespace battleState.control {
      class gamesource.battleState.control.CardMotionControl {
          - curAngle : float
          - loc : Vector2f
          - rotateDir : float
          - rotateSpeed : float
          - speedFactor : float
          - step : Vector2f
          - tarAngle : float
          - target : Vector2f
          - walkDir : Vector2f
          - walkSpeed : float
          - z : float
          + CardMotionControl()
          + CardMotionControl()
          + setSpatial()
          + setTarget()
          + setWalkSpeed()
          # controlRender()
          # controlUpdate()
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.control {
      class gamesource.battleState.control.UseCardControl {
          - loc : Vector2f
          - rotateSpeed : float
          - rotatedist : float
          - speedFactor : float
          - stage : int
          - step : Vector2f
          - target : Vector2f
          - walkDir : Vector2f
          - walkSpeed : float
          - z : float
          + UseCardControl()
          + UseCardControl()
          + setSpatial()
          + setSpeedFactor()
          + setTarget()
          + setWalkSpeed()
          # controlRender()
          # controlUpdate()
      }
    }
  }
  

  gamesource.battleState.control.CardMotionControl -up-|> com.jme3.scene.control.AbstractControl
  gamesource.battleState.control.UseCardControl -up-|> com.jme3.scene.control.AbstractControl


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
