@startuml

title __EQUIPMENT's Class Diagram__\n

  namespace gamesource {
    namespace battleState.equipment {
      class gamesource.battleState.equipment.CreateEquipment {
          {static} - getCommonEquipment : double
          {static} - getEpicEquipment : double
          {static} - getLegendaryEquipment : double
          {static} - getRareEquipment : double
          {static} - isChange : boolean
          {static} - proArr : double[]
          {static} + getRandomCommonEquipment()
          {static} + getRandomEpicEquipment()
          {static} + getRandomEquipment()
          {static} + getRandomLegendaryEquipment()
          {static} + getRandomRareEquipment()
          {static} + setGetCommonEquipment()
          {static} + setGetEpicEquipment()
          {static} + setGetLegendaryEquipment()
          {static} + setGetRareEquipment()
          {static} - setProArr()
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      class gamesource.battleState.equipment.Equipment {
          # description : String
          # enemies : ArrayList<Enemy>
          # imgSrc : String
          # name : String
          # picName : String
          + Equipment()
          + fun()
          + getDegree()
          + getDescription()
          + getEnemies()
          + getImgSrc()
          + getName()
          + getOpportunity()
          + getPicName()
          + resetBuff()
          + setDegree()
          + setDescription()
          + setEnemies()
          + setImage()
          + setImgSrc()
          + setName()
          + setOpportunity()
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      enum EquipmentDegree {
        COMMON
        EPIC
        LEGENDARY
        RARE
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      enum Opportunity {
        ATTACK
        DEAD
        ENDB
        ENDT
        GET
        GETCARD
        GETD
        SHOP
        STARTB
        STARTT
        USE
      }
    }
  }
  

  gamesource.battleState.equipment.Equipment -up-|> com.jme3.ui.Picture
  gamesource.battleState.equipment.Equipment o-- gamesource.battleState.equipment.Equipment.EquipmentDegree : degree
  gamesource.battleState.equipment.Equipment o-- gamesource.battleState.equipment.Equipment.Opportunity : op
  gamesource.battleState.equipment.Equipment +-down- gamesource.battleState.equipment.Equipment.EquipmentDegree
  gamesource.battleState.equipment.Equipment +-down- gamesource.battleState.equipment.Equipment.Opportunity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
