@startuml

title __GAMESOURCE's Class Diagram__\n

  namespace gamesource {
    class gamesource.App {
        {static} + guan : int
        {static} + world : String
        {static} + world2 : String
        - inputListener : RawInputListener
        - juchi : int
        - open : int
        - shadow : int
        - state : AppStateManager
        + App()
        {static} + main()
        + simpleInitApp()
        + skyBox()
        + skyBox2()
        - changeCursor()
        - getPicture()
        - initEffect()
    }
  }
  

  namespace gamesource {
    class gamesource.App.StartTalk {
        + onAction()
    }
  }
  

  namespace gamesource {
    class gamesource.app2 {
        {static} + main()
    }
  }
  

  namespace gamesource {
    class gamesource.start {
        + Start()
        {static} + main()
    }
  }
  

  gamesource.App -up-|> com.jme3.app.SimpleApplication
  gamesource.App o-- gamesource.State.worldState.FirstState : f1
  gamesource.App o-- gamesource.State.worldState.SecondState : f2
  gamesource.App o-- gamesource.State.worldState.ThirdState : f3
  gamesource.App o-- gamesource.State.worldState.ForthState : f4
  gamesource.App o-- gamesource.State.worldState.FifthState : f5
  gamesource.App o-- gamesource.State.worldState.SixthState : f6
  gamesource.App o-- gamesource.testState.First : t1
  gamesource.App o-- gamesource.App.StartTalk : st
  gamesource.App +-down- gamesource.App.StartTalk
  gamesource.App.StartTalk .up.|> com.jme3.input.controls.ActionListener




@enduml
