@startuml

title __UISTATE's Class Diagram__\n

  namespace gamesource {
    namespace uiState {
      class gamesource.uiState.ChestFind {
          - app : SimpleApplication
          - cardUIs : CardUI[]
          - cards : ArrayList<Card>
          - window : Container
          + ChestFind()
          # calculatePreferLocation()
          # cleanup()
          # initialize()
          # onDisable()
          # onEnable()
      }
    }
  }
  

  namespace gamesource {
    namespace uiState {
      class gamesource.uiState.ChestFind.CloseCommand {
          + execute()
      }
    }
  }
  

  namespace gamesource {
    namespace uiState {
      class gamesource.uiState.SmallMap {
          - app : SimpleApplication
          - height : float
          - isShowMap : boolean
          - point : Container
          - size : Vector2f
          - stage : int
          - width : float
          - window : Container
          + SmallMap()
          + getMapCenter()
          + update()
          # calculatePreferLocation()
          # cleanup()
          # initialize()
          # onDisable()
          # onEnable()
      }
    }
  }
  

  namespace gamesource {
    namespace uiState {
      class gamesource.uiState.SmallMap.SmallMapListener {
          + onAction()
      }
    }
  }
  

  gamesource.uiState.ChestFind -up-|> com.jme3.app.state.BaseAppState
  gamesource.uiState.ChestFind o-- gamesource.uiState.ChestFind.CloseCommand : closeCommand
  gamesource.uiState.ChestFind +-down- gamesource.uiState.ChestFind.CloseCommand
  gamesource.uiState.ChestFind.CloseCommand .up.|> com.simsilica.lemur.Command
  gamesource.uiState.SmallMap -up-|> com.jme3.app.state.BaseAppState
  gamesource.uiState.SmallMap o-- gamesource.State.CharacterState.MajorActor : majorActor
  gamesource.uiState.SmallMap +-down- gamesource.uiState.SmallMap.SmallMapListener
  gamesource.uiState.SmallMap.SmallMapListener .up.|> com.jme3.input.controls.ActionListener




@enduml
