@startuml

title __POWER's Class Diagram__\n

  namespace gamesource {
    namespace battleState.card {
      namespace saber.power {
        class gamesource.battleState.card.saber.power.CounterStrikeGesture {
            + CounterStrikeGesture()
            + CounterStrikeGesture()
            + upgrade()
            + use()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.card {
      namespace saber.power {
        class gamesource.battleState.card.saber.power.DivineDefense {
            + DivineDefense()
            + DivineDefense()
            + upgrade()
            + use()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.card {
      namespace saber.power {
        class gamesource.battleState.card.saber.power.HideTheSword {
            + HideTheSword()
            + HideTheSword()
            + upgrade()
            + use()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.card {
      namespace saber.power {
        class gamesource.battleState.card.saber.power.ManaBoost {
            + ManaBoost()
            + ManaBoost()
            + upgrade()
            + use()
        }
      }
    }
  }
  

  gamesource.battleState.card.saber.power.CounterStrikeGesture -up-|> gamesource.battleState.card.PowerCard
  gamesource.battleState.card.saber.power.DivineDefense -up-|> gamesource.battleState.card.PowerCard
  gamesource.battleState.card.saber.power.HideTheSword -up-|> gamesource.battleState.card.PowerCard
  gamesource.battleState.card.saber.power.ManaBoost -up-|> gamesource.battleState.card.PowerCard




@enduml
