@startuml

title __CHARACTERSTATE's Class Diagram__\n

  namespace gamesource {
    namespace State {
      namespace CharacterState {
        class gamesource.State.CharacterState.MajorActor {
            {static} + BACKWARD : String
            {static} + DEBUG : String
            {static} + FORWARD : String
            {static} + JUMP : String
            {static} + LEFT : String
            {static} + RIGHT : String
            - CamSituation : int
            - MajorStar : Spatial
            - animChannel : AnimChannel
            - animControl : AnimControl
            - app : SimpleApplication
            - bip001 : Node
            - bullet : BulletAppState
            - cam : Camera
            - camDir : Vector3f
            - camLeft : Vector3f
            - camNode : Node
            - camPlace : Vector3f
            - camRot : Quaternion
            - camSituation2 : int
            - capsuleShape : CapsuleCollisionShape
            - character : Node
            - chaseCam : ChaseCamera
            - down : boolean
            - flycam : FlyByCamera
            - height : float
            - inputManager : InputManager
            - jump : float
            - left : boolean
            - major : BoundingVolume
            - physics : PhysicsSpace
            - place : Vector3f
            - player : CharacterControl
            - radius : float
            - ray : Ray
            - right : boolean
            - rootNode : Node
            - run : AudioNode
            - scene : Node
            - stepHeight : float
            - up : boolean
            - walkDir : Vector3f
            - walkDirection : Vector3f
            + MajorActor()
            + MajorActor()
            + change()
            + change2()
            + get()
            + getMajor()
            + getX()
            + getY()
            + getZ()
            + height()
            + idle()
            + initAnim()
            + initModel()
            + initMusic()
            + initPhysics()
            + jump()
            + mouseChange()
            + onAnimChange()
            + onAnimCycleDone()
            + setPlace()
            + update()
            + walk()
            # cleanup()
            # initialize()
            # onDisable()
            # onEnable()
            - initChaseCamera()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace State {
      namespace CharacterState {
        class gamesource.State.CharacterState.Master1 {
            - animChannel : AnimChannel
            - animControl : AnimControl
            - app : SimpleApplication
            - bip001 : Node
            - bullet : BulletAppState
            - capsuleShape : CapsuleCollisionShape
            - character : Node
            - girl : Spatial
            - girlControl : CharacterControl
            - height : float
            - master : BoundingVolume
            - modelY : float
            - physics : PhysicsSpace
            - place : Vector3f
            - radius : float
            - rootNode : Node
            - rotateX : float
            - rotateY : float
            - rotateZ : float
            - scene : Node
            - stepHeight : float
            + Master1()
            + Master1()
            + Master1()
            + get()
            + initAnim()
            + initModel()
            + initPhysics()
            + onAction()
            # cleanup()
            # initialize()
            # onDisable()
            # onEnable()
        }
      }
    }
  }
  

  gamesource.State.CharacterState.MajorActor .up.|> com.jme3.animation.AnimEventListener
  gamesource.State.CharacterState.MajorActor -up-|> com.jme3.app.state.BaseAppState
  gamesource.State.CharacterState.Master1 .up.|> com.jme3.input.controls.ActionListener
  gamesource.State.CharacterState.Master1 -up-|> com.jme3.app.state.BaseAppState




@enduml
