@startuml

title __DRAGONWAT's Class Diagram__\n

  namespace gamesource {
    namespace battleState.character {
      namespace enemy.dragonWat {
        class gamesource.battleState.character.enemy.dragonWat.DarkDragon {
            + DarkDragon()
            + enemyAction()
            + startTurn()
            + updateHints()
            # attack()
            # attack2()
            # getBlessing()
            # getBlockAndAttack()
            # getBlocks()
            # releaseBuff()
            # releaseCurses()
            # releaseDebuff()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.character {
      namespace enemy.dragonWat {
        class gamesource.battleState.character.enemy.dragonWat.EliteDarkDragon {
            + EliteDarkDragon()
            + enemyAction()
            + startTurn()
            + updateHints()
            # attack()
            # attack2()
            # getBlessing()
            # getBlockAndAttack()
            # getBlocks()
            # releaseBuff()
            # releaseCurses()
            # releaseDebuff()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.character {
      namespace enemy.dragonWat {
        class gamesource.battleState.character.enemy.dragonWat.KingDarkDragon {
            + KingDarkDragon()
            + enemyAction()
            + startTurn()
            + updateHints()
            # attack()
            # attack2()
            # getBlessing()
            # getBlockAndAttack()
            # getBlocks()
            # releaseBuff()
            # releaseCurses()
            # releaseDebuff()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.character {
      namespace enemy.dragonWat {
        class gamesource.battleState.character.enemy.dragonWat.RampageDarkDragon {
            + RampageDarkDragon()
            + enemyAction()
            + startTurn()
            + updateHints()
            # attack()
            # attack2()
            # getBlessing()
            # getBlockAndAttack()
            # getBlocks()
            # releaseBuff()
            # releaseCurses()
            # releaseDebuff()
        }
      }
    }
  }
  

  gamesource.battleState.character.enemy.dragonWat.DarkDragon -up-|> gamesource.battleState.character.Enemy
  gamesource.battleState.character.enemy.dragonWat.EliteDarkDragon -up-|> gamesource.battleState.character.Enemy
  gamesource.battleState.character.enemy.dragonWat.KingDarkDragon -up-|> gamesource.battleState.character.Enemy
  gamesource.battleState.character.enemy.dragonWat.RampageDarkDragon -up-|> gamesource.battleState.character.Enemy



@enduml
