@startuml

title __BATTLE's Class Diagram__\n

  namespace gamesource {
    namespace battleState.battle {
      class gamesource.battleState.battle.Battle {
          {static} + BAG : Trigger
          {static} + CHANGECAMERA : Trigger
          {static} + MOVE : Trigger
          {static} + TALK : Trigger
          {static} + bag : String
          {static} + change : String
          {static} + move : String
          {static} + talk : String
          ~ ambient : AmbientLight
          ~ sun : DirectionalLight
          - State : ArrayList<BaseAppState>
          - app : SimpleApplication
          - inputManager : InputManager
          - state : AppStateManager
          + Battle()
          + Battle()
          + addLight()
          # cleanup()
          # initialize()
          # onDisable()
          # onEnable()
          - getPicture()
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.battle {
      class gamesource.battleState.battle.Cards {
          - card : Picture
          {static} + main()
          + simpleInitApp()
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.battle {
      class gamesource.battleState.battle.Cards.MyRawInputListener {
          + beginInput()
          + endInput()
          + onJoyAxisEvent()
          + onJoyButtonEvent()
          + onKeyEvent()
          + onMouseButtonEvent()
          + onMouseMotionEvent()
          + onTouchEvent()
      }
    }
  }
  


  

  gamesource.battleState.battle.Battle -up-|> com.jme3.app.state.BaseAppState
  gamesource.battleState.battle.Battle o-- gamesource.battleState.appState.BattleState : b1
  gamesource.battleState.battle.Battle o-- gamesource.State.controlState.InputAppState : input
  gamesource.battleState.battle.Cards -up-|> com.jme3.app.SimpleApplication
  gamesource.battleState.battle.Cards +-down- gamesource.battleState.battle.Cards.MyRawInputListener
  gamesource.battleState.battle.Cards.MyRawInputListener .up.|> com.jme3.input.RawInputListener





@enduml
