@startuml

title __INITIALINTERFACE's Class Diagram__\n

  namespace gamesource {
    namespace initialinterface {
      class gamesource.initialinterface.Main_test {
          {static} + cartoon()
          {static} + main()
          {static} + start()
          {static} + start_game()
      }
    }
  }
  

  namespace gamesource {
    namespace initialinterface {
      class gamesource.initialinterface.StartInterface {
          {static} - window : RenderWindow
          {static} + click_compute()
          {static} + init()
          {static} + set_text()
      }
    }
  }
  

  namespace gamesource {
    namespace initialinterface {
      class gamesource.initialinterface.Test {
          {static} + aliase : String
          {static} + cartoon : Sprite
          {static} + frame_user : int
          {static} + init : boolean
          {static} + screenx : int
          {static} + screeny : int
          {static} + shadow_user : String
          {static} + texture_c : Texture_init[]
          {static} + texture_cartoon : Texture[]
          {static} + window : RenderWindow
          {static} - aliasing1 : Sprite
          {static} - aliasing2 : Sprite
          {static} - aliasing3 : Sprite
          {static} - aliasing4 : Sprite
          {static} - aliasing5 : Sprite
          {static} - aliasing6 : Sprite
          {static} - chapter : int
          {static} - chapter1 : Sprite
          {static} - chapter2 : Sprite
          {static} - chapter3 : Sprite
          {static} - chapter4 : Sprite
          {static} - chapter5 : Sprite
          {static} - chapter6 : Sprite
          {static} - chapter7 : Sprite
          {static} - character : Sprite
          {static} - frame1 : Sprite
          {static} - frame2 : Sprite
          {static} - frame3 : Sprite
          {static} - full : boolean
          {static} - map2 : Sprite
          {static} - resolution1 : Sprite
          {static} - resolution2 : Sprite
          {static} - resolution3 : Sprite
          {static} - resolution4 : Sprite
          {static} - shadow1 : Sprite
          {static} - shadow2 : Sprite
          {static} - shadow3 : Sprite
          {static} - shadow4 : Sprite
          {static} + background_control()
          {static} + click_compute()
          {static} + run()
          {static} + set_text()
      }
    }
  }
  

  namespace gamesource {
    namespace initialinterface {
      class gamesource.initialinterface.Texture_init {
          - path : String
          - texture_return : Texture
          + Texture_init()
          + get_texture()
      }
    }
  }
  

  namespace gamesource {
    namespace initialinterface {
      class gamesource.initialinterface.User_data {
          {static} + aliase : String
          {static} + chapter : int
          {static} + frame_user : int
          {static} + full : boolean
          {static} + screenx : int
          {static} + screeny : int
          {static} + shadow_user : String
          {static} + getAliase()
          {static} + getChapter()
          {static} + getFrame_user()
          {static} + getFull()
          {static} + getScreenx()
          {static} + getScreeny()
          {static} + getShadow_user()
          {static} + passData()
      }
    }
  }
  




@enduml
