@startuml

title __EPIC's Class Diagram__\n

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.ArmstrongGun {
            + ArmstrongGun()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.InvisibilityCloak {
            - count : int
            + InvisibilityCloak()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.Kaleidoscope {
            + Kaleidoscope()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.LampOfAladdin {
            + LampOfAladdin()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.TheFlagOfTheFFRegiment {
            + TheFlagOfTheFFRegiment()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.ThreeYearSimulationFiveYearCollegeEntranceExamination {
            - count : int
            + ThreeYearSimulationFiveYearCollegeEntranceExamination()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.WYRSteamAccount {
            + WYRSteamAccount()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.WalletOfGSW {
            - work : boolean
            + WalletOfGSW()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.WeightBearing {
            + WeightBearing()
            + fun()
        }
      }
    }
  }
  

  namespace gamesource {
    namespace battleState.equipment {
      namespace epic {
        class gamesource.battleState.equipment.epic.WomenClothesOfCYX {
            ~ work : boolean
            + WomenClothesOfCYX()
            + fun()
        }
      }
    }
  }
  

  gamesource.battleState.equipment.epic.ArmstrongGun -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.InvisibilityCloak -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.Kaleidoscope -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.LampOfAladdin -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.TheFlagOfTheFFRegiment -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.ThreeYearSimulationFiveYearCollegeEntranceExamination -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.WYRSteamAccount -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.WalletOfGSW -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.WeightBearing -up-|> gamesource.battleState.equipment.Equipment
  gamesource.battleState.equipment.epic.WomenClothesOfCYX -up-|> gamesource.battleState.equipment.Equipment


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
