@startuml

title __STATE's Class Diagram__\n

  namespace gamesource {
    namespace State {
      class gamesource.State.sandState {
          + Scene : Spatial
          + landScape : RigidBodyControl
          + physics : PhysicsSpace
          + sceneShape : CollisionShape
          - app : SimpleApplication
          - rootNode : Node
          # cleanup()
          # initialize()
          # onDisable()
          # onEnable()
      }
    }
  }
  

  gamesource.State.sandState -up-|> com.jme3.app.state.BaseAppState




@enduml
